# Generated by Django 4.0.4 on 2022-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lightsoff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='temperature',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='passes',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
