# Generated by Django 4.0.4 on 2022-05-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lightsoff', '0002_alter_light_temperature_alter_passes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='power',
            field=models.PositiveIntegerField(default=100, verbose_name='Power in watts'),
        ),
    ]
